version: 2.1

jobs:
  testing:
    docker:
      - image: cimg/base:stable

    working_directory: ~/playwright_workshop

    steps:
      - checkout

      # Install NVM
      - run:
          name: Install NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

      # Source NVM and install Node.js
      - run:
          name: Install Node and PW deps
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install 18
            nvm use 18
            npm install
            npx playwright install
            npx playwright install-deps

      - run:
          name: Spin up example-app and Execute PW tests
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"tion
            nvm install 18
            nvm use 18
            cd example_app
            npx http-server &
            cd ..
            npx playwright test tests/ --trace on

      # Export test reports
      - run:
          name: Export Test Reports
          command: |
            mkdir -p ~/artifacts
            cp -r playwright-report ~/artifacts/
            cp -r test-results ~/artifacts/

      # Save test artifacts
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .

      - store_artifacts:
          path: playwright-report
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - testing
