version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Use an appropriate Node.js version

    working_directory: ~/playwright_workshop

    steps:
      - checkout

      # Install Node.js
      - run:
          name: Install Node.js
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Spin up local app (customize this step based on your app setup)
      - run:
          name: Start Local App
          command: |
            cd example_app
            npm start &

      # Run Playwright tests
      - run:
          name: Run Playwright Tests
          command: |
            pwd
            ls
            npx playwright install chromium
            npx playwright test tests/ --trace on

      # Export test reports
      - run:
          name: Export Test Reports
          command: |
            mkdir -p ~/artifacts
            cp -r playwright-report ~/artifacts/
            cp -r test-results ~/artifacts/

      # Save test artifacts
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .

workflows:
  version: 2
  build:
    jobs:
      - build
